import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { PassThrough, Writable } from "node:stream";
import { describe, expect, it } from "vitest";

import type { Finding } from "../src/check.js";

import { runApply } from "../src/apply.js";
import { assertBlockedState } from "../src/blocked.js";
import { copyrightYears, renderTemplate, upsertSection } from "../src/branding.js";
import { runCheck } from "../src/check.js";
import { initCommand } from "../src/cli.js";
import {
  detectFirstCommitYear,
  detectPlatform,
  InitError,
  parsePlatformChoice,
  parsePlatformFlag,
  parseSinceFlag,
  parseVisibilityChoice,
  parseVisibilityFlag,
  runInit,
} from "../src/init.js";
// Aliased: several tests destructure `getPackageRoot` from a dynamic import.
import { loadManifest, getPackageRoot as standardsRoot } from "../src/manifest.js";
import { isMarkdownThemerReadme, readRepoMeta } from "../src/repo.js";
import {
  assertPendingPayload,
  buildPendingPayload,
  matchesPlatform,
  writePending,
} from "../src/sync.js";

const YEAR = 2026;

describe("copyrightYears", () => {
  it("renders a single year when since equals current", () => {
    expect(copyrightYears(YEAR, YEAR)).toBe("2026");
  });

  it("renders a range when since is older", () => {
    expect(copyrightYears(2011, YEAR)).toBe("2011&ndash;2026");
  });
});

describe("renderTemplate", () => {
  it("replaces known variables and keeps unknown ones", () => {
    expect(renderTemplate("a {{x}} b {{y}}", { x: "1" })).toBe("a 1 b {{y}}");
  });
});

describe("upsertSection", () => {
  it("appends a missing section with a separator", () => {
    const result = upsertSection("# Title\n", "m", "body");
    expect(result.action).toBe("appended");
    expect(result.content).toContain("<!-- m:start -->\n\nbody\n\n<!-- m:end -->");
    expect(result.content).toContain("\n---\n");
  });

  it("keeps a blank line before the end marker so oxfmt does not fight apply", () => {
    const body = "- one\n- two";
    const appended = upsertSection("# Title\n", "m", body);
    expect(appended.content).toContain(`${body}\n\n<!-- m:end -->`);
    // Re-running against the formatter-stable shape must be a no-op.
    expect(upsertSection(appended.content, "m", body).action).toBe("unchanged");
  });

  it("replaces an outdated section in place", () => {
    const old = upsertSection("# Title\n", "m", "old").content;
    const result = upsertSection(old, "m", "new");
    expect(result.action).toBe("replaced");
    expect(result.content).toContain("new");
    expect(result.content).not.toContain("old");
  });

  it("reports unchanged when the section is current", () => {
    const current = upsertSection("# Title\n", "m", "same").content;
    expect(upsertSection(current, "m", "same").action).toBe("unchanged");
  });
});

function createFixtureRepo(): string {
  const cwd = mkdtempSync(join(tmpdir(), "standards-test-"));
  writeFileSync(join(cwd, "package.json"), "{}\n");
  writeFileSync(join(cwd, "README.md"), "# Demo\n");
  writeFileSync(
    join(cwd, ".repometa.json"),
    `${JSON.stringify({ standards: 0, visibility: "oss", since: 2020, platform: "github" }, undefined, 2)}\n`,
  );
  return cwd;
}

function configureMarkdownThemer(cwd: string): void {
  writeFileSync(join(cwd, "README.md.src"), "# Source\n");
  writeFileSync(
    join(cwd, "README.md"),
    "<!-- This file is generated by markdown-themer. Edit README.md.src instead. -->\n\n# Source\n",
  );
  writeFileSync(join(cwd, "markdown-themer.config.ts"), "export default { themes: [] };\n");
  writeFileSync(
    join(cwd, "package.json"),
    `${JSON.stringify(
      {
        scripts: {
          "readme:write": "markdown-themer --write",
          "readme:check": "markdown-themer --check",
          "agent:check": "pnpm readme:check",
        },
      },
      undefined,
      2,
    )}\n`,
  );
  mkdirSync(join(cwd, ".github", "workflows"), { recursive: true });
  writeFileSync(
    join(cwd, ".github", "workflows", "ci.yml"),
    "steps:\n  - run: pnpm readme:check\n",
  );
}

describe("apply and check", () => {
  it("brings a fresh node repo up to standards and detects drift afterwards", () => {
    const cwd = createFixtureRepo();

    const changes = runApply(cwd, YEAR);
    const paths = changes.map((change) => change.path);
    expect(paths).toContain(".oxfmtrc.json");
    expect(paths).toContain("eslint.config.ts");
    expect(paths).toContain("README.md");
    expect(paths).toContain("AGENTS.md");
    expect(paths).toContain(".repometa.json");
    expect(paths).toContain("SECURITY.md");
    expect(paths).toContain("CODE_OF_CONDUCT.md");
    expect(paths).toContain("SUPPORT.md");
    expect(paths).toContain("CLAUDE.md");
    expect(paths).toContain(".github/CODEOWNERS");
    expect(paths).toContain(".github/ISSUE_TEMPLATE/bug_report.yml");
    expect(paths).toContain(".github/pull_request_template.md");

    const readme = readFileSync(join(cwd, "README.md"), "utf8");
    expect(readme).toContain("sebastian-software-branding:start");
    expect(readme).toContain("2020&ndash;2026");

    const agents = readFileSync(join(cwd, "AGENTS.md"), "utf8");
    expect(agents).toContain("sebastian-software-consumer-agents:start");
    expect(agents).toContain("Do not hand-edit managed files");

    expect(runCheck(cwd, YEAR)).toStrictEqual([]);

    writeFileSync(join(cwd, ".oxfmtrc.json"), "{}\n");
    const findings = runCheck(cwd, YEAR);
    expect(findings).toHaveLength(1);
    expect(findings[0]?.kind).toBe("managed");

    const repaired = runApply(cwd, YEAR);
    expect(repaired).toHaveLength(1);
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("detects drift in the consumer AGENTS section", () => {
    const cwd = createFixtureRepo();

    runApply(cwd, YEAR);
    writeFileSync(
      join(cwd, "AGENTS.md"),
      "<!-- sebastian-software-consumer-agents:start -->\nstale\n<!-- sebastian-software-consumer-agents:end -->\n",
    );

    const findings = runCheck(cwd, YEAR);
    expect(findings).toHaveLength(1);
    expect(findings[0]).toMatchObject({
      kind: "section",
      path: "AGENTS.md",
      detail: 'section "sebastian-software-consumer-agents" is outdated',
    });
  });

  it("uses the plain footer for private repositories and keeps seeded files untouched", () => {
    const cwd = createFixtureRepo();
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify({ standards: 0, visibility: "private", since: YEAR }, undefined, 2)}\n`,
    );
    writeFileSync(join(cwd, "eslint.config.ts"), "// custom local config\n");

    runApply(cwd, YEAR);

    const readme = readFileSync(join(cwd, "README.md"), "utf8");
    expect(readme).toContain("All rights reserved");
    expect(readme).not.toContain("Work with us");
    expect(readFileSync(join(cwd, "eslint.config.ts"), "utf8")).toBe("// custom local config\n");
  });

  it("leaves README branding to an explicit markdown-themer owner", () => {
    const cwd = createFixtureRepo();
    configureMarkdownThemer(cwd);
    const customReadme = readFileSync(join(cwd, "README.md"), "utf8");
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify(
        {
          standards: 0,
          visibility: "oss",
          since: 2020,
          platform: "github",
          readme: { owner: "markdown-themer" },
        },
        undefined,
        2,
      )}\n`,
    );

    const changes = runApply(cwd, YEAR);
    expect(changes.map((change) => change.path)).not.toContain("README.md");
    expect(readFileSync(join(cwd, "README.md"), "utf8")).toBe(customReadme);
    expect(readFileSync(join(cwd, "AGENTS.md"), "utf8")).toContain(
      "sebastian-software-consumer-agents:start",
    );
    expect(runCheck(cwd, YEAR).some((finding) => finding.path === "README.md")).toBe(false);
    expect(isMarkdownThemerReadme(readRepoMeta(cwd))).toBe(true);
  });

  it("reports invalid markdown-themer prerequisites and never repairs its README", () => {
    const cwd = createFixtureRepo();
    const customReadme = readFileSync(join(cwd, "README.md"), "utf8");
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify(
        { standards: 0, visibility: "oss", since: 2020, readme: { owner: "markdown-themer" } },
        undefined,
        2,
      )}\n`,
    );

    expect(() => runApply(cwd, YEAR)).toThrow(/Invalid markdown-themer README migration/);
    expect(readFileSync(join(cwd, "README.md"), "utf8")).toBe(customReadme);
    const findings = runCheck(cwd, YEAR);
    expect(
      findings.filter((finding) => finding.kind === "readme").map((finding) => finding.path),
    ).toStrictEqual(
      expect.arrayContaining(["README.md", "markdown-themer.config.*", "package.json"]),
    );
    const syncResult = runCli(["sync", "--cwd", cwd, "--dry-run"]);
    expect(syncResult.status).toBe(1);
    expect(syncResult.stderr).toContain("Invalid markdown-themer README migration");
    expect(readFileSync(join(cwd, "README.md"), "utf8")).toBe(customReadme);
  });

  it("reports legacy branding markers while preserving the generated README", () => {
    const cwd = createFixtureRepo();
    configureMarkdownThemer(cwd);
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify(
        { standards: 0, visibility: "oss", since: 2020, readme: { owner: "markdown-themer" } },
        undefined,
        2,
      )}\n`,
    );
    const before = readFileSync(join(cwd, "README.md"), "utf8");
    writeFileSync(
      join(cwd, "README.md"),
      `${before}\n<!-- sebastian-software-branding:start -->\n`,
    );
    writeFileSync(
      join(cwd, "README.md.src"),
      "# Source\n\n<!-- sebastian-software-branding:start -->\n",
    );
    const findings = runCheck(cwd, YEAR);
    expect(
      findings.some((finding) => finding.detail.includes("legacy sebastian-software-branding")),
    ).toBe(true);
    expect(findings.some((finding) => finding.path === "README.md.src")).toBe(true);
    expect(() => runApply(cwd, YEAR)).toThrow(/legacy sebastian-software-branding/);
    expect(readFileSync(join(cwd, "README.md"), "utf8")).toContain(
      "sebastian-software-branding:start",
    );
  });

  it("allows prose that mentions the legacy branding name", () => {
    const cwd = createFixtureRepo();
    configureMarkdownThemer(cwd);
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify(
        { standards: 0, visibility: "oss", since: 2020, readme: { owner: "markdown-themer" } },
        undefined,
        2,
      )}\n`,
    );
    writeFileSync(
      join(cwd, "README.md"),
      "<!-- This file is generated by markdown-themer. Edit README.md.src instead. -->\n\nWe discuss sebastian-software-branding here.\n",
    );
    writeFileSync(
      join(cwd, "README.md.src"),
      "# Source\n\nWe discuss sebastian-software-branding here.\n",
    );
    expect(runCheck(cwd, YEAR).filter((finding) => finding.kind === "readme")).toStrictEqual([]);
  });

  it("rejects an unsupported README owner", () => {
    const cwd = createFixtureRepo();
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify(
        { standards: 0, visibility: "oss", since: 2020, readme: { owner: "other" } },
        undefined,
        2,
      )}\n`,
    );
    expect(() => readRepoMeta(cwd)).toThrow(/readme\.owner/);
  });
});

const COMMUNITY_FILES = ["SECURITY.md", "CODE_OF_CONDUCT.md", "SUPPORT.md", "CLAUDE.md"];

const GITHUB_COMMUNITY_FILES = [
  ".github/CODEOWNERS",
  ".github/ISSUE_TEMPLATE/bug_report.yml",
  ".github/ISSUE_TEMPLATE/feature_request.yml",
  ".github/ISSUE_TEMPLATE/question.yml",
  ".github/ISSUE_TEMPLATE/config.yml",
  ".github/pull_request_template.md",
];

describe("common community files", () => {
  it("seeds every community file on a github repo and then reports no drift", () => {
    const cwd = createFixtureRepo();

    runApply(cwd, YEAR);

    for (const file of [...COMMUNITY_FILES, ...GITHUB_COMMUNITY_FILES]) {
      expect(existsSync(join(cwd, file))).toBe(true);
    }
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("seeds CLAUDE.md as a bare AGENTS.md pointer", () => {
    const cwd = createFixtureRepo();

    runApply(cwd, YEAR);

    expect(readFileSync(join(cwd, "CLAUDE.md"), "utf8")).toBe("@AGENTS.md\n");
  });

  it("names both private reporting channels and a supported-versions rule that cannot go stale", () => {
    const cwd = createFixtureRepo();

    runApply(cwd, YEAR);

    const security = readFileSync(join(cwd, "SECURITY.md"), "utf8");
    expect(security).toContain("security@sebastian-software.de");
    expect(security).toContain("Report a vulnerability");
    expect(security).toContain("the latest release on the default branch");
  });

  it("disables blank issues and keeps seeded files free of per-repo URLs", () => {
    const cwd = createFixtureRepo();

    runApply(cwd, YEAR);

    expect(readFileSync(join(cwd, ".github/ISSUE_TEMPLATE/config.yml"), "utf8")).toContain(
      "blank_issues_enabled: false",
    );
    // Seeded files are copied verbatim (`applySeeded` never calls
    // `renderTemplate`), so no reference may hardcode a repository name.
    for (const file of [...COMMUNITY_FILES, ...GITHUB_COMMUNITY_FILES]) {
      expect(readFileSync(join(cwd, file), "utf8")).not.toContain("github.com/sebastian-software/");
    }
  });

  it("offers a security route the issue chooser can render", () => {
    const cwd = createFixtureRepo();

    runApply(cwd, YEAR);

    const chooser = readFileSync(join(cwd, ".github/ISSUE_TEMPLATE/config.yml"), "utf8");
    const urls = chooser
      .split("\n")
      .map((line) => /^ *url: (?<url>\S+)$/u.exec(line)?.groups?.url)
      .filter((url) => url !== undefined);

    // GitHub drops a contact link whose URL is not http(s) — a `mailto:` entry
    // would vanish from the chooser exactly where the advisory route is
    // unavailable too, so the address lives in the `about` text instead.
    expect(urls.length).toBeGreaterThanOrEqual(2);
    for (const url of urls) {
      expect(url).toMatch(/^https?:\/\//u);
    }
    expect(chooser).toContain("security@sebastian-software.de");
  });

  it("keeps an existing community file untouched", () => {
    const cwd = createFixtureRepo();
    writeFileSync(join(cwd, "SECURITY.md"), "# Custom policy\n");

    runApply(cwd, YEAR);

    expect(readFileSync(join(cwd, "SECURITY.md"), "utf8")).toBe("# Custom policy\n");
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("skips the github-scoped community files on a forgejo repo", () => {
    const cwd = createFixtureRepo();
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify({ standards: 0, visibility: "oss", since: 2020, platform: "forgejo" }, undefined, 2)}\n`,
    );

    runApply(cwd, YEAR);

    for (const file of COMMUNITY_FILES) {
      expect(existsSync(join(cwd, file))).toBe(true);
    }
    for (const file of GITHUB_COMMUNITY_FILES) {
      expect(existsSync(join(cwd, file))).toBe(false);
    }
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });
});

type LabelEntry = { color: string; description: string; name: string };
type PrefixEntry = { color: string; description: string; prefix: string };
type Migration = { from: string; to: string };

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isUnknownArray(value: unknown): value is unknown[] {
  return Array.isArray(value);
}

function readString(entry: Record<string, unknown>, key: string): string {
  const value = entry[key];
  if (typeof value !== "string" || value === "") {
    throw new TypeError(`labels.json: entry is missing a non-empty "${key}"`);
  }
  return value;
}

function readEntries(raw: Record<string, unknown>, key: string): Array<Record<string, unknown>> {
  const value = raw[key];
  if (!isUnknownArray(value)) {
    throw new TypeError(`labels.json: "${key}" is not an array`);
  }
  return value.map((entry) => {
    if (!isRecord(entry)) {
      throw new TypeError(`labels.json: "${key}" contains a non-object entry`);
    }
    return entry;
  });
}

function readTaxonomy(packageRoot: string): {
  labels: LabelEntry[];
  migrations: Migration[];
  prefixes: PrefixEntry[];
} {
  const raw: unknown = JSON.parse(
    readFileSync(join(packageRoot, "reference/common/labels.json"), "utf8"),
  );
  if (!isRecord(raw)) {
    throw new TypeError("labels.json is not an object");
  }
  return {
    labels: readEntries(raw, "labels").map((entry) => ({
      color: readString(entry, "color"),
      description: readString(entry, "description"),
      name: readString(entry, "name"),
    })),
    migrations: readEntries(raw, "migrations").map((entry) => ({
      from: readString(entry, "from"),
      to: readString(entry, "to"),
    })),
    prefixes: readEntries(raw, "prefixes").map((entry) => ({
      color: readString(entry, "color"),
      description: readString(entry, "description"),
      prefix: readString(entry, "prefix"),
    })),
  };
}

function createRustFixtureRepo(cargo = "[workspace]\n"): string {
  const cwd = mkdtempSync(join(tmpdir(), "standards-rust-"));
  writeFileSync(join(cwd, "Cargo.toml"), cargo);
  writeFileSync(join(cwd, "README.md"), "# Demo\n");
  writeFileSync(
    join(cwd, ".repometa.json"),
    `${JSON.stringify({ standards: 0, visibility: "oss", since: 2020, platform: "github" }, undefined, 2)}\n`,
  );
  return cwd;
}

const RUST_FILES = ["rustfmt.toml", "rust-toolchain.toml", "deny.toml"];

function rustScopeSources(): string[] {
  const scope = loadManifest(standardsRoot()).scopes.rust;
  if (scope === undefined) {
    throw new Error("manifest.json declares no rust scope");
  }
  return [...scope.managed, ...scope.seeded].map((entry) => entry.source);
}

// A git action is pinned by a 40-hex commit SHA with the version in a trailing
// comment; a `docker://` action by an immutable `@sha256:` digest, since an
// image tag can be moved just like a git tag.
const SHA_PINNED_ACTION = /^[^@\s]+@[0-9a-f]{40} # .+$/u;
const DIGEST_PINNED_IMAGE = /^docker:\/\/[^@\s]+@sha256:[0-9a-f]{64}$/u;

function isPinnedActionRef(reference: string): boolean {
  if (reference.startsWith("docker://")) {
    // The image tag before the digest carries the version, so a trailing
    // comment is optional here.
    return DIGEST_PINNED_IMAGE.test(reference.replace(/ # .*$/u, ""));
  }
  return SHA_PINNED_ACTION.test(reference);
}

function workflowActionRefs(workflow: string): string[] {
  // YAML indents with spaces; `\s*` here would let the anchor scan past newlines.
  return [...workflow.matchAll(/^ *- uses: (?<ref>.+)$/gmu)].map((match) => {
    const reference = match.groups?.ref;
    if (reference === undefined) {
      throw new Error("named capture group did not match");
    }
    return reference;
  });
}

describe("nested node workspaces", () => {
  const WORKSPACE_FILES = [
    ".oxfmtrc.json",
    "eslint.config.ts",
    "oxlint.config.ts",
    "tsconfig.json",
    "cspell.json",
  ];

  function createWorkspaceRepo(workspaces: string[], directories = workspaces): string {
    const cwd = createRustFixtureRepo();
    for (const directory of directories) {
      mkdirSync(join(cwd, directory), { recursive: true });
      writeFileSync(join(cwd, directory, "package.json"), "{}\n");
    }
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify({ standards: 0, visibility: "oss", since: 2020, platform: "github", workspaces }, undefined, 2)}\n`,
    );
    return cwd;
  }

  it("writes the node scope into a declared workspace, not into the root", () => {
    const cwd = createWorkspaceRepo(["node"]);

    const paths = runApply(cwd, YEAR).map((change) => change.path);

    for (const file of WORKSPACE_FILES) {
      expect(paths).toContain(join("node", file));
      expect(existsSync(join(cwd, "node", file))).toBe(true);
      expect(existsSync(join(cwd, file))).toBe(false);
    }
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("keeps repository-level files out of the workspace", () => {
    const cwd = createWorkspaceRepo(["node"]);

    runApply(cwd, YEAR);

    // renovate.json and the CI workflow belong to the repository, and the
    // common scope is repository-wide — a workspace gets none of them.
    for (const file of ["renovate.json", ".github/workflows/ci.yml", ...COMMUNITY_FILES]) {
      expect(existsSync(join(cwd, "node", file))).toBe(false);
    }
    expect(existsSync(join(cwd, "SECURITY.md"))).toBe(true);
    expect(readFileSync(join(cwd, "node", "package.json"), "utf8")).toBe("{}\n");
  });

  it("reports a workspace file with its full path", () => {
    const cwd = createWorkspaceRepo(["node"]);
    runApply(cwd, YEAR);
    writeFileSync(join(cwd, "node", ".oxfmtrc.json"), "{}\n");

    expect(runCheck(cwd, YEAR)).toStrictEqual([
      {
        kind: "managed",
        path: join("node", ".oxfmtrc.json"),
        detail: "managed file differs from reference",
        blocking: false,
      },
    ]);
  });

  it("handles several workspaces, including a nested path", () => {
    const cwd = createWorkspaceRepo(["node", "crates/tool-node"]);

    runApply(cwd, YEAR);

    expect(existsSync(join(cwd, "node", ".oxfmtrc.json"))).toBe(true);
    expect(existsSync(join(cwd, "crates/tool-node", ".oxfmtrc.json"))).toBe(true);
  });

  it("ignores a nested package.json that is not declared", () => {
    // A vendored mirror or a generated sidecar carries a package.json too;
    // only what the repository declares is managed.
    const cwd = createWorkspaceRepo(["node"], ["node", "node/vendor/upstream"]);

    runApply(cwd, YEAR);

    expect(existsSync(join(cwd, "node/vendor/upstream", ".oxfmtrc.json"))).toBe(false);
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("leaves a repository without workspaces exactly as it was", () => {
    const cwd = createRustFixtureRepo();
    mkdirSync(join(cwd, "node"));
    writeFileSync(join(cwd, "node", "package.json"), "{}\n");

    runApply(cwd, YEAR);

    expect(existsSync(join(cwd, "node", ".oxfmtrc.json"))).toBe(false);
    expect(existsSync(join(cwd, ".oxfmtrc.json"))).toBe(false);
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("gives a workspace repository the node changelog entries", async () => {
    const { buildPendingPayload: buildPayload } = await import("../src/sync.js");
    const cwd = createWorkspaceRepo(["node"]);

    const payload = buildPayload(cwd, 0);

    expect(payload?.scopes).toStrictEqual(["common", "node", "rust"]);
    // 0001 is the Prettier-to-oxfmt migration; a Rust repository with a Node
    // workspace has to read it like any other Node package.
    expect(payload?.changes.map((entry) => entry.version)).toContain(1);
  });

  it.each([["/absolute"], [".."], ["node/../.."], ["."], [""]])(
    "rejects the workspace path %j",
    (workspace) => {
      const cwd = createWorkspaceRepo([workspace], []);

      expect(() => runCheck(cwd, YEAR)).toThrow(/workspaces must be relative paths/u);
    },
  );

  it("rejects a workspace that resolves outside the repository", () => {
    // Path validation is lexical; a declared directory can still be a symlink
    // pointing out of the checkout, and `apply` writes files into it.
    const outside = mkdtempSync(join(tmpdir(), "standards-outside-"));
    writeFileSync(join(outside, "package.json"), "{}\n");
    const cwd = createWorkspaceRepo(["node"], []);
    symlinkSync(outside, join(cwd, "node"), "dir");

    expect(() => runCheck(cwd, YEAR)).toThrow(/outside the repository/u);
    expect(() => runApply(cwd, YEAR)).toThrow(/outside the repository/u);
    expect(existsSync(join(outside, ".oxfmtrc.json"))).toBe(false);
  });

  it("accepts a symlinked workspace that stays inside the repository", () => {
    const cwd = createWorkspaceRepo(["link"], ["packages/tool"]);
    symlinkSync(join(cwd, "packages/tool"), join(cwd, "link"), "dir");

    runApply(cwd, YEAR);

    expect(existsSync(join(cwd, "packages/tool", ".oxfmtrc.json"))).toBe(true);
  });

  it("ignores a scope that has nothing to contribute to a workspace", async () => {
    // A Cargo.toml inside a declared Node workspace detects the rust scope
    // there, but no rust entry applies in a workspace — so it must not write
    // files and must not schedule rust changelog entries either.
    const { buildPendingPayload: buildPayload } = await import("../src/sync.js");
    const cwd = createWorkspaceRepo(["node"]);
    writeFileSync(join(cwd, "node", "Cargo.toml"), "[package]\n");

    runApply(cwd, YEAR);

    expect(existsSync(join(cwd, "node", "rustfmt.toml"))).toBe(false);
    expect(buildPayload(cwd, 8)?.changes.map((entry) => entry.version)).toStrictEqual([
      9, 10, 11, 12, 13,
    ]);
  });

  it("rejects a duplicate workspace declaration", () => {
    const cwd = createWorkspaceRepo(["node", "node"], ["node"]);

    expect(() => runCheck(cwd, YEAR)).toThrow(/duplicate entries/u);
  });

  it("applies a repeated workspace once when the metadata bypasses validation", () => {
    // `runApply` accepts pre-read metadata, so the invariant cannot rest on
    // the file's validation alone.
    const cwd = createWorkspaceRepo(["node"]);
    const meta = {
      standards: 0,
      visibility: "oss",
      since: 2020,
      platform: "github",
      workspaces: ["node", "node/", "node"],
    } as const;

    const paths = runApply(cwd, YEAR, {
      preReadMeta: { ...meta, workspaces: [...meta.workspaces] },
    }).map((change) => change.path);

    expect(paths.filter((path) => path === join("node", ".oxfmtrc.json"))).toHaveLength(1);
  });

  it("rejects a workspaces value that is not an array of strings", () => {
    const cwd = createRustFixtureRepo();
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify({ standards: 0, visibility: "oss", since: 2020, platform: "github", workspaces: "node" })}\n`,
    );

    expect(() => runCheck(cwd, YEAR)).toThrow(/workspaces must be an array of strings/u);
  });
});

describe("rust scope", () => {
  it("detects a virtual workspace and seeds the toolchain files", () => {
    const cwd = createRustFixtureRepo();

    const paths = runApply(cwd, YEAR).map((change) => change.path);

    expect(paths).toStrictEqual(expect.arrayContaining(RUST_FILES));
    // No package.json, so nothing from the node scope may land.
    expect(existsSync(join(cwd, "eslint.config.ts"))).toBe(false);
    expect(existsSync(join(cwd, ".oxfmtrc.json"))).toBe(false);
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("detects a root package as well as a workspace", () => {
    const cwd = createRustFixtureRepo('[package]\nname = "demo"\n');

    runApply(cwd, YEAR);

    for (const file of RUST_FILES) {
      expect(existsSync(join(cwd, file))).toBe(true);
    }
  });

  it("leaves rust files out of a repository without Cargo.toml", () => {
    const cwd = createFixtureRepo();

    runApply(cwd, YEAR);

    for (const file of RUST_FILES) {
      expect(existsSync(join(cwd, file))).toBe(false);
    }
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("repairs a drifted rustfmt.toml because it is managed", () => {
    const cwd = createRustFixtureRepo();
    runApply(cwd, YEAR);
    writeFileSync(join(cwd, "rustfmt.toml"), 'edition = "2021"\n');

    const findings = runCheck(cwd, YEAR);
    expect(findings).toHaveLength(1);
    expect(findings[0]).toMatchObject({ kind: "managed", path: "rustfmt.toml" });

    runApply(cwd, YEAR);
    expect(readFileSync(join(cwd, "rustfmt.toml"), "utf8")).toContain('edition = "2024"');
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("keeps a reviewed deny.toml and a pinned toolchain untouched", () => {
    const cwd = createRustFixtureRepo();
    const deny = '[licenses]\nexceptions = [{ allow = ["ISC"], crate = "ring" }]\n';
    const toolchain = '[toolchain]\nchannel = "1.93"\n';
    writeFileSync(join(cwd, "deny.toml"), deny);
    writeFileSync(join(cwd, "rust-toolchain.toml"), toolchain);

    runApply(cwd, YEAR);

    expect(readFileSync(join(cwd, "deny.toml"), "utf8")).toBe(deny);
    expect(readFileSync(join(cwd, "rust-toolchain.toml"), "utf8")).toBe(toolchain);
    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
  });

  it("ships the CI and publish skeletons as reference files only", () => {
    const sources = rustScopeSources();
    expect(sources).not.toContain("reference/rust/ci.yml");
    // Publishing moved next to the release templates once it grew npm and
    // native jobs; neither file is seeded.
    expect(existsSync(join(standardsRoot(), "reference/rust/publish.yml"))).toBe(false);
    expect(sources).not.toContain("reference/release-please/publish-skeleton.yml");

    const cwd = createRustFixtureRepo();
    runApply(cwd, YEAR);
    expect(existsSync(join(cwd, ".github/workflows/ci.yml"))).toBe(false);
    expect(existsSync(join(cwd, ".github/workflows/publish.yml"))).toBe(false);
  });

  it.each(["reference/rust/ci.yml", "reference/release-please/publish-skeleton.yml"])(
    "pins every action in %s",
    (file) => {
      const workflow = readFileSync(join(standardsRoot(), file), "utf8");

      const uses = workflowActionRefs(workflow);
      expect(uses.length).toBeGreaterThan(0);
      expect(uses.filter((reference) => !isPinnedActionRef(reference))).toStrictEqual([]);
    },
  );

  it("holds docker actions to a digest, not an image tag", () => {
    const sha = "0".repeat(40);
    const digest = "f".repeat(64);

    expect(isPinnedActionRef(`actions/checkout@${sha} # v7.0.1`)).toBe(true);
    expect(isPinnedActionRef("actions/checkout@v7")).toBe(false);
    expect(isPinnedActionRef(`actions/checkout@${sha}`)).toBe(false);
    expect(isPinnedActionRef(`docker://ghcr.io/org/tool:1.2.3@sha256:${digest}`)).toBe(true);
    expect(isPinnedActionRef(`docker://ghcr.io/org/tool@sha256:${digest} # 1.2.3`)).toBe(true);
    expect(isPinnedActionRef("docker://ghcr.io/org/tool:1.2.3")).toBe(false);
    expect(isPinnedActionRef("docker://ghcr.io/org/tool:latest")).toBe(false);
    expect(isPinnedActionRef(`docker://ghcr.io/org/tool@${sha}`)).toBe(false);
  });

  it("binds the manual publish path to a release tag", () => {
    const workflow = readFileSync(
      join(standardsRoot(), "reference/release-please/publish-skeleton.yml"),
      "utf8",
    );

    const dispatch = workflow.slice(
      workflow.indexOf("  workflow_dispatch:"),
      workflow.indexOf("\npermissions:"),
    );
    expect(dispatch).toContain("    inputs:\n      tag:\n");
    expect(dispatch).toContain("        required: true\n");
    expect(workflow).toMatch(
      /ref: \$\{\{ inputs\.tag \|\| needs\.release-please\.outputs\.tag_name \}\}/u,
    );
    expect(workflow).not.toMatch(/ref: main/u);
  });

  it("documents the scope instead of deferring it", () => {
    const guide = readFileSync(join(standardsRoot(), "reference/rust/README.md"), "utf8");

    expect(guide).not.toContain("Not yet defined");
    expect(guide).toContain("Edition 2024");
    expect(guide).toContain("four stable releases behind current stable");
    expect(guide).toContain("MIT OR Apache-2.0");
    expect(guide).toContain("BSD-2-Clause");
    expect(guide).toContain("rustdoc-args");
    expect(guide).toContain("Cargo.lock");
  });

  it("reads the MSRV through cargo instead of a regex over Cargo.toml", () => {
    const ci = readFileSync(join(standardsRoot(), "reference/rust/ci.yml"), "utf8");

    expect(ci).toContain("cargo metadata --no-deps --format-version 1");
    expect(ci).not.toContain("sed -n");
    // `rust-toolchain.toml` outranks the default toolchain; the lane must override it.
    expect(ci).toContain("rustup override set");
  });

  it("lets release-please carry the pinned CLI in the reference drift lane", () => {
    const lines = readFileSync(join(standardsRoot(), "reference/rust/ci.yml"), "utf8").split("\n");
    const pinned = lines.filter((line) => line.includes("dlx @sebastian-software/standards@"));

    expect(pinned).toHaveLength(1);
    // The generic updater rewrites every annotated line, so a second one — a
    // comment explaining the pin, say — is a rewrite target nobody intended.
    expect(lines.filter((line) => line.includes("x-release-please-version"))).toHaveLength(1);
    // A published tarball must never tell a Rust repository to run a CLI older
    // than the `manifest.json#currentVersion` that same tarball ships, and the
    // stale-CLI mismatch is a blocking finding. release-please bumps the pin in
    // the very pull request that bumps `package.json`, so the two stay equal.
    expect(pinned[0]).toContain(`@sebastian-software/standards@${readOwnPackageVersion()} `);
    // Nothing else keeps them in step: without the annotation and the
    // `extra-files` entry the literal freezes at whatever was released last.
    expect(pinned[0]).toContain("x-release-please-version");

    expect(readReleasePleaseExtraFiles()).toContainEqual({
      // `.yml` would otherwise pick the YAML updater, which needs a jsonpath;
      // the annotation is only read by the generic updater.
      type: "generic",
      path: "reference/rust/ci.yml",
    });
  });
});

describe("label taxonomy", () => {
  it("declares unique labels with six-digit hex colors", async () => {
    const { getPackageRoot } = await import("../src/manifest.js");
    const taxonomy = readTaxonomy(getPackageRoot());

    const names = taxonomy.labels.map((entry) => entry.name);
    expect(new Set(names).size).toBe(names.length);
    for (const entry of taxonomy.labels) {
      expect(entry.color).toMatch(/^[0-9a-f]{6}$/u);
    }
    expect(names).toStrictEqual(
      expect.arrayContaining([
        "type:bug",
        "type:feature",
        "type:docs",
        "type:chore",
        "priority:P0",
        "priority:P1",
        "priority:P2",
        "priority:P3",
        "epic",
        "cross-repo",
        "good first issue",
        "dependencies",
      ]),
    );
    expect(taxonomy.prefixes.map((entry) => entry.prefix)).toStrictEqual(["area:"]);
  });

  it("maps every legacy spelling onto a defined label or prefix", async () => {
    const { getPackageRoot } = await import("../src/manifest.js");
    const taxonomy = readTaxonomy(getPackageRoot());

    const targets = new Set([
      ...taxonomy.labels.map((entry) => entry.name),
      ...taxonomy.prefixes.map((entry) => entry.prefix),
    ]);
    for (const migration of taxonomy.migrations) {
      expect(targets.has(migration.to)).toBe(true);
      expect(targets.has(migration.from)).toBe(false);
    }
    expect(taxonomy.migrations.map((entry) => entry.from)).toStrictEqual(
      expect.arrayContaining(["priority:low", "priority: P2", "P3", "category:"]),
    );
  });

  it("only applies labels the taxonomy defines from the seeded issue forms", async () => {
    const { getPackageRoot } = await import("../src/manifest.js");
    const packageRoot = getPackageRoot();
    const names = new Set(readTaxonomy(packageRoot).labels.map((entry) => entry.name));

    const forms = [
      { file: "github-issue-template-bug-report.yml", label: "type:bug" },
      { file: "github-issue-template-feature-request.yml", label: "type:feature" },
      { file: "github-issue-template-question.yml", label: "question" },
    ];
    for (const { file, label } of forms) {
      expect(names.has(label)).toBe(true);
      expect(readFileSync(join(packageRoot, "reference/common", file), "utf8")).toContain(label);
    }
  });
});

describe("selectChanges and buildPrompt", () => {
  it("filters changelog entries by version and scope", async () => {
    const { selectChanges } = await import("../src/changes.js");
    const { getPackageRoot } = await import("../src/manifest.js");
    const root = getPackageRoot();

    // 0013 is node+rust, so a common-only repository does not receive it.
    expect(selectChanges(root, 0, ["common"]).map((entry) => entry.version)).toStrictEqual([
      1, 2, 3, 7, 8, 9, 10, 11, 12,
    ]);
    expect(selectChanges(root, 1, ["common", "node"]).map((entry) => entry.version)).toStrictEqual([
      2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
    ]);
    expect(selectChanges(root, 8, ["common", "node"]).map((entry) => entry.version)).toStrictEqual([
      9, 10, 11, 12, 13,
    ]);
    // 0009 is the first entry a rust-only repository ever receives.
    expect(selectChanges(root, 0, ["rust"]).map((entry) => entry.version)).toStrictEqual([
      9, 11, 13,
    ]);
  });

  it("builds an agent prompt containing skill and changelog", async () => {
    const { buildPrompt } = await import("../src/agent.js");
    const { selectChanges } = await import("../src/changes.js");
    const { getPackageRoot } = await import("../src/manifest.js");
    const root = getPackageRoot();

    const changes = selectChanges(root, 0, ["common", "node"]);
    const prompt = buildPrompt({
      packageRoot: root,
      meta: { standards: 1, visibility: "oss", since: 2020 },
      scopeNames: ["common", "node"],
      fromVersion: 0,
      toVersion: 2,
      changes,
    });

    expect(prompt).toContain("repository standards — agent instructions");
    expect(prompt).toContain("0001-baseline.md");
    expect(prompt).toContain("0002-renovate-pending.md");
    expect(prompt).toContain("0003-platform-aware-ci.md");
    expect(prompt).toContain("visibility: oss");
    // inline mode embeds the full changelog bodies — the positive
    // counterpart to the pending-file test, which asserts they are absent.
    expect(changes.length).toBeGreaterThan(0);
    for (const entry of changes) {
      expect(entry.content.trim().length).toBeGreaterThan(0);
      expect(prompt).toContain(entry.content.trim());
    }
  });

  it("instructs the agent to run the gate in CI mode as non-blocking hints", async () => {
    const { buildPrompt } = await import("../src/agent.js");
    const { selectChanges } = await import("../src/changes.js");
    const { getPackageRoot } = await import("../src/manifest.js");
    const root = getPackageRoot();

    const prompt = buildPrompt({
      packageRoot: root,
      meta: { standards: 1, visibility: "oss", since: 2020 },
      scopeNames: ["common", "node"],
      fromVersion: 0,
      toVersion: 2,
      changes: selectChanges(root, 0, ["common", "node"]),
    });

    expect(prompt).toContain("## Validation");
    expect(prompt).toContain("pnpm agent:check:ci");
    expect(prompt).toContain("pnpm agent:check");
    expect(prompt).toContain("Do not stop at the first failing check");
    // Checks are hints, not a merge gate: commits are never withheld.
    expect(prompt).toContain("never withhold or revert your commits");
  });

  it("forces CI mode in the agent environment, overriding any inherited CI", async () => {
    const { buildAgentEnv } = await import("../src/agent.js");

    expect(buildAgentEnv({}).CI).toBe("true");
    expect(buildAgentEnv({ CI: "false" }).CI).toBe("true");
    expect(buildAgentEnv({ PATH: "/usr/bin" }).PATH).toBe("/usr/bin");
  });

  it("references the pending.json changes array instead of embedding bodies", async () => {
    const { buildPrompt } = await import("../src/agent.js");
    const { selectChanges } = await import("../src/changes.js");
    const { getPackageRoot } = await import("../src/manifest.js");
    const root = getPackageRoot();
    const changes = selectChanges(root, 0, ["common", "node"]);

    const prompt = buildPrompt({
      packageRoot: root,
      meta: { standards: 1, visibility: "oss", since: 2020 },
      scopeNames: ["common", "node"],
      fromVersion: 0,
      toVersion: 2,
      changes,
      changesSource: "pending-file",
    });

    expect(prompt).toContain(".standards/pending.json");
    expect(prompt).toContain("0001-baseline.md (v1)");
    expect(prompt).toContain("## Validation");
    // No changelog body is embedded — bodies live only in changes[].content.
    expect(changes.length).toBeGreaterThan(0);
    for (const entry of changes) {
      expect(entry.content.trim().length).toBeGreaterThan(0);
      expect(prompt).not.toContain(entry.content.trim());
    }
  });

  it("requires the pin alignment as the first step of a pending-file run", async () => {
    const { buildPrompt } = await import("../src/agent.js");
    const { selectChanges } = await import("../src/changes.js");
    const { getPackageRoot } = await import("../src/manifest.js");
    const root = getPackageRoot();

    const prompt = buildPrompt({
      packageRoot: root,
      meta: { standards: 1, visibility: "oss", since: 2020 },
      scopeNames: ["common", "node"],
      fromVersion: 0,
      toVersion: 13,
      cliVersion: "9.9.9",
      changes: selectChanges(root, 0, ["common", "node"]),
      changesSource: "pending-file",
    });

    expect(prompt).toContain("Pre-flight: align the CLI with the version stamp");
    expect(prompt).toContain("9.9.9");
    expect(prompt).toContain("never infer compatibility from npm");
    expect(prompt).toContain("exits 3");
    // The pre-flight runs before the judgement steps it validates.
    expect(prompt.indexOf("Pre-flight: align the CLI")).toBeLessThan(
      prompt.indexOf("## Changelog entries to execute"),
    );
    // The old, false claim that apply always leaves the stamp correct is gone.
    expect(prompt).not.toContain("branding section and the version stamp are up to date");
  });

  it("omits the pin instruction for an inline run, whose CLI may be the stale one", async () => {
    const { buildPrompt } = await import("../src/agent.js");
    const { selectChanges } = await import("../src/changes.js");
    const { getPackageRoot } = await import("../src/manifest.js");
    const root = getPackageRoot();

    const prompt = buildPrompt({
      packageRoot: root,
      meta: { standards: 1, visibility: "oss", since: 2020 },
      scopeNames: ["common", "node"],
      fromVersion: 0,
      toVersion: 13,
      cliVersion: "9.9.9",
      changes: selectChanges(root, 0, ["common", "node"]),
    });

    expect(prompt).not.toContain("Pre-flight: align the CLI");
    expect(prompt).not.toContain("9.9.9");
  });

  it("instructs the agent to write and clear the blocked marker in both modes", async () => {
    const { buildPrompt } = await import("../src/agent.js");
    const { selectChanges } = await import("../src/changes.js");
    const { getPackageRoot } = await import("../src/manifest.js");
    const root = getPackageRoot();

    for (const changesSource of ["inline", "pending-file"] as const) {
      const prompt = buildPrompt({
        packageRoot: root,
        meta: { standards: 1, visibility: "oss", since: 2020 },
        scopeNames: ["common", "node"],
        fromVersion: 0,
        toVersion: 13,
        changes: selectChanges(root, 0, ["common", "node"]),
        changesSource,
      });

      // Unique to the Validation block, so the SKILL text embedded above
      // cannot satisfy the assertion on its own.
      expect(prompt).toContain("Publication is not validated completion");
      expect(prompt).toContain("still failing or incomplete after your best-effort");
      expect(prompt).toContain("delete `.standards/blocked.json` when");
      expect(prompt).toContain("Writing the marker never replaces pushing");
      // The always-push rule from #37 stays verbatim.
      expect(prompt).toContain("never withhold or revert your commits");
    }
  });

  it("instructs run 1 to post an information comment for failed or incomplete checks", async () => {
    const { buildPrompt } = await import("../src/agent.js");
    const { selectChanges } = await import("../src/changes.js");
    const { getPackageRoot } = await import("../src/manifest.js");
    const root = getPackageRoot();

    const prompt = buildPrompt({
      packageRoot: root,
      meta: { standards: 1, visibility: "oss", since: 2020 },
      scopeNames: ["common", "node"],
      fromVersion: 0,
      toVersion: 2,
      changes: selectChanges(root, 0, ["common", "node"]),
    });

    expect(prompt).toContain("information comment");
    expect(prompt).toContain("could not complete");
    // Context-bound anchor for the env-prerequisites note (unique to this bullet).
    expect(prompt).toContain("may lack prerequisites");
    expect(prompt).toContain("environment variables");
    // Conditional: no comment when everything passes.
    expect(prompt).toContain("post no such comment");
    // The distinguishing clauses vs. #38: additive and finalize-preserving.
    expect(prompt).toContain("in addition to the summary");
    expect(prompt).toContain("always-finalize");
  });
});

function hashTree(root: string): Map<string, string> {
  const hashes = new Map<string, string>();
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      const handler = entry.isDirectory()
        ? walk
        : (path: string): void => {
            hashes.set(
              relative(root, path),
              createHash("sha256").update(readFileSync(path)).digest("hex"),
            );
          };
      handler(full);
    }
  };
  walk(root);
  return hashes;
}

function readStamp(cwd: string): number {
  const raw: unknown = JSON.parse(readFileSync(join(cwd, ".repometa.json"), "utf8"));
  if (typeof raw !== "object" || raw === null || !("standards" in raw)) {
    throw new Error("invalid .repometa.json");
  }
  const value = (raw as Record<string, unknown>).standards;
  if (typeof value !== "number") {
    throw new TypeError("standards is not a number");
  }
  return value;
}

function unwrap<T>(value: T | undefined): T {
  if (value === undefined) {
    throw new Error("expected defined value");
  }
  return value;
}

const CONTRACT_PREFIXES = [
  ".oxfmtrc.json",
  "eslint.config.ts",
  "oxlint.config.ts",
  "tsconfig.json",
  "cspell.json",
  "renovate.json",
  ".repometa.json",
  "README.md",
  "AGENTS.md",
  "CLAUDE.md",
  "SECURITY.md",
  "CODE_OF_CONDUCT.md",
  "SUPPORT.md",
  "rustfmt.toml",
  "rust-toolchain.toml",
  "deny.toml",
  ".standards/",
  ".github/",
];

function withinContract(path: string): boolean {
  return CONTRACT_PREFIXES.some(
    (prefix) => path === prefix || (prefix.endsWith("/") && path.startsWith(prefix)),
  );
}

function readOwnPackageVersion(): string {
  const raw: unknown = JSON.parse(readFileSync(join(standardsRoot(), "package.json"), "utf8"));
  const version = isRecord(raw) ? raw.version : undefined;
  if (typeof version !== "string" || version === "") {
    throw new TypeError("package.json: version is not a non-empty string");
  }
  return version;
}

/**
 * The `extra-files` release-please rewrites for the root package. Narrowing
 * lives here so the test that reads it stays free of conditionals.
 */
function readReleasePleaseExtraFiles(): unknown[] {
  const raw: unknown = JSON.parse(
    readFileSync(join(standardsRoot(), "release-please-config.json"), "utf8"),
  );
  const packages = isRecord(raw) ? raw.packages : undefined;
  const rootPackage = isRecord(packages) ? packages["."] : undefined;
  const extraFiles = isRecord(rootPackage) ? rootPackage["extra-files"] : undefined;
  if (!Array.isArray(extraFiles)) {
    throw new TypeError('release-please-config.json: packages["."].extra-files is not an array');
  }
  return extraFiles;
}

describe("buildPendingPayload", () => {
  it("emits a schema-versioned payload when changes are pending", () => {
    const cwd = createFixtureRepo();
    const payload = unwrap(buildPendingPayload(cwd, 0));
    expect(payload).toMatchObject({
      schemaVersion: 1,
      fromVersion: 0,
      visibility: "oss",
      exceptions: [],
    });
    expect(payload.toVersion).toBeGreaterThanOrEqual(2);
    expect(payload.scopes).toContain("common");
    expect(payload.scopes).toContain("node");
    expect(payload.prompt).toContain("repository standards — agent instructions");
    expect(payload.changes.length).toBeGreaterThan(0);
    expect(payload.changes.every((entry) => typeof entry.content === "string")).toBe(true);
    // The prompt references the changes array; it does not duplicate the
    // changelog bodies, which live only in changes[].content.
    expect(payload.prompt).toContain(".standards/pending.json");
    for (const entry of payload.changes) {
      expect(entry.content.trim().length).toBeGreaterThan(0);
      expect(payload.prompt).not.toContain(entry.content.trim());
    }
  });

  it("records the npm version of the CLI that produced the payload", () => {
    const cwd = createFixtureRepo();

    const payload = unwrap(buildPendingPayload(cwd, 0));

    // Additive: the schema version does not move, so a payload already in
    // flight when this field appeared stays readable.
    expect(payload.schemaVersion).toBe(1);
    expect(payload.cliVersion).toBe(readOwnPackageVersion());
  });

  it("returns undefined when the stamp matches the manifest", () => {
    const cwd = createFixtureRepo();
    runApply(cwd, YEAR);
    const stamp = readStamp(cwd);
    expect(stamp).toBeGreaterThanOrEqual(2);
    expect(buildPendingPayload(cwd, stamp)).toBeUndefined();
  });

  it("uses explicit fromVersion even when .repometa.json was already bumped", () => {
    const cwd = createFixtureRepo();
    runApply(cwd, YEAR);

    const payload = unwrap(buildPendingPayload(cwd, 0));
    expect(payload.fromVersion).toBe(0);
    expect(payload.changes.length).toBeGreaterThan(0);
  });
});

describe("assertPendingPayload", () => {
  const validPayload = {
    schemaVersion: 1,
    fromVersion: 0,
    toVersion: 2,
    scopes: ["common", "node"],
    visibility: "oss",
    exceptions: [],
    prompt: "prompt body",
    changes: [
      {
        file: "0001-baseline.md",
        version: 1,
        scopes: ["common", "node"],
        content: "changelog body",
      },
    ],
  };

  it("accepts a payload built by buildPendingPayload after a structured clone", () => {
    const cwd = createFixtureRepo();
    const payload = unwrap(buildPendingPayload(cwd, 0));
    const clone: unknown = structuredClone(payload);
    expect(() => {
      assertPendingPayload(clone);
    }).not.toThrow();
  });

  it("accepts a manually constructed valid payload with empty changes", () => {
    const empty = { ...validPayload, changes: [] };
    expect(() => {
      assertPendingPayload(empty);
    }).not.toThrow();
  });

  it("accepts a payload written before cliVersion existed", () => {
    // `cliVersion` was added without a schema bump, so an in-flight payload
    // that predates it must not be rejected.
    expect(() => {
      assertPendingPayload(validPayload);
    }).not.toThrow();
  });

  it("rejects a payload whose cliVersion is not a string", () => {
    const bad = { ...validPayload, cliVersion: 10 };
    expect(() => {
      assertPendingPayload(bad);
    }).toThrow(/cliVersion/);
  });

  it("rejects a payload with the wrong schemaVersion", () => {
    const bad = { ...validPayload, schemaVersion: 2 };
    expect(() => {
      assertPendingPayload(bad);
    }).toThrow(/schemaVersion/);
  });

  it("rejects a payload with a missing required field", () => {
    const { fromVersion, ...rest } = validPayload;
    void fromVersion;
    expect(() => {
      assertPendingPayload(rest);
    }).toThrow(/fromVersion/);
  });

  it("rejects a payload where scopes is not an array of strings", () => {
    const bad = { ...validPayload, scopes: "common" };
    expect(() => {
      assertPendingPayload(bad);
    }).toThrow(/scopes/);
  });

  it("rejects a payload with an unknown visibility value", () => {
    const bad = { ...validPayload, visibility: "internal" };
    expect(() => {
      assertPendingPayload(bad);
    }).toThrow(/visibility/);
  });

  it("rejects a payload with a malformed changes entry", () => {
    const bad = {
      ...validPayload,
      changes: [{ file: "x.md", version: 1, scopes: ["common"] }],
    };
    expect(() => {
      assertPendingPayload(bad);
    }).toThrow(/changes\[0\]\.content/);
  });
});

describe("writePending", () => {
  it("writes the schema-versioned marker at the resolved path", () => {
    const cwd = createFixtureRepo();
    const payload = buildPendingPayload(cwd, 0);
    writePending(cwd, ".standards/pending.json", payload);

    const path = join(cwd, ".standards/pending.json");
    expect(existsSync(path)).toBe(true);
    const parsed: unknown = JSON.parse(readFileSync(path, "utf8"));
    expect(parsed).toMatchObject({ schemaVersion: 1, fromVersion: 0 });
  });

  it("removes a stale marker when no payload is pending", () => {
    const cwd = createFixtureRepo();
    runApply(cwd, YEAR);
    const path = join(cwd, ".standards/pending.json");
    mkdirSync(join(cwd, ".standards"), { recursive: true });
    writeFileSync(path, "{}\n", "utf8");

    writePending(cwd, ".standards/pending.json", undefined);

    expect(existsSync(path)).toBe(false);
  });

  it("is a no-op when no payload is pending and no marker exists", () => {
    const cwd = createFixtureRepo();
    runApply(cwd, YEAR);
    const path = join(cwd, ".standards/pending.json");

    writePending(cwd, ".standards/pending.json", undefined);

    expect(existsSync(path)).toBe(false);
  });
});

describe("preReadMeta threading", () => {
  it("runApply with and without preReadMeta produces identical changes", () => {
    const cwdA = createFixtureRepo();
    const cwdB = createFixtureRepo();
    const meta = {
      standards: 0,
      visibility: "oss" as const,
      since: 2020,
      platform: "github" as const,
    };

    const changesDefault = runApply(cwdA, YEAR);
    const changesParameterized = runApply(cwdB, YEAR, { preReadMeta: meta });

    expect(
      changesParameterized.map((change) => change.path).sort((a, b) => a.localeCompare(b)),
    ).toStrictEqual(changesDefault.map((change) => change.path).sort((a, b) => a.localeCompare(b)));
  });

  it("buildPendingPayload with and without preReadMeta produces identical payloads", () => {
    const cwd = createFixtureRepo();
    const meta = {
      standards: 0,
      visibility: "oss" as const,
      since: 2020,
      platform: "github" as const,
    };

    const payloadWithoutMeta = unwrap(buildPendingPayload(cwd, 0));
    const payloadWithMeta = unwrap(buildPendingPayload(cwd, 0, meta));

    expect(payloadWithMeta).toStrictEqual(payloadWithoutMeta);
  });
});

describe("apply write contract", () => {
  it("modifies only contract-allowed paths", () => {
    const cwd = createFixtureRepo();

    const foreign = ["src/x.ts", ".gitignore", "docs/notes.md"];
    foreign.forEach((rel) => {
      const target = join(cwd, rel);
      mkdirSync(join(target, ".."), { recursive: true });
      writeFileSync(target, `foreign:${rel}\n`);
    });

    const before = hashTree(cwd);
    runApply(cwd, YEAR);
    const after = hashTree(cwd);

    const modifiedPaths = [...after.entries()]
      .filter(([path, hash]) => before.get(path) !== hash)
      .map(([path]) => path);
    const removedPaths = [...before.keys()].filter((path) => !after.has(path));
    const violators = [...modifiedPaths, ...removedPaths].filter((path) => !withinContract(path));
    expect(violators).toStrictEqual([]);

    const preservedForeign = foreign.map((rel) => readFileSync(join(cwd, rel), "utf8"));
    expect(preservedForeign).toStrictEqual(foreign.map((rel) => `foreign:${rel}\n`));
  });
});

function createFreshDir(): string {
  return mkdtempSync(join(tmpdir(), "standards-init-"));
}

function runGit(cwd: string, args: string[], env?: NodeJS.ProcessEnv): void {
  const result = spawnSync("git", ["-C", cwd, ...args], {
    encoding: "utf8",
    env,
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.error !== undefined) {
    throw new Error(`git ${args.join(" ")} failed to spawn: ${result.error.message}`);
  }
  if (result.status !== 0) {
    const stderr = result.stderr.trim();
    throw new Error(`git ${args.join(" ")} exited with status ${String(result.status)}: ${stderr}`);
  }
}

function initGitRepo(cwd: string, commitYear: number): void {
  const env = {
    ...process.env,
    GIT_AUTHOR_NAME: "Test",
    GIT_AUTHOR_EMAIL: "test@example.com",
    GIT_COMMITTER_NAME: "Test",
    GIT_COMMITTER_EMAIL: "test@example.com",
    GIT_AUTHOR_DATE: `${String(commitYear)}-01-15T12:00:00`,
    GIT_COMMITTER_DATE: `${String(commitYear)}-01-15T12:00:00`,
  };
  runGit(cwd, ["init", "--quiet", "--initial-branch=main"], env);
  writeFileSync(join(cwd, "README.md"), "# fixture\n");
  runGit(cwd, ["add", "README.md"], env);
  runGit(cwd, ["commit", "--quiet", "-m", "initial"], env);
}

describe("parseVisibilityFlag", () => {
  it("accepts the two long forms", () => {
    expect(parseVisibilityFlag("oss")).toBe("oss");
    expect(parseVisibilityFlag("private")).toBe("private");
  });

  it("rejects short forms and anything else", () => {
    expect(() => parseVisibilityFlag("o")).toThrow(InitError);
    expect(() => parseVisibilityFlag("p")).toThrow(InitError);
    expect(() => parseVisibilityFlag("internal")).toThrow(InitError);
    expect(() => parseVisibilityFlag("")).toThrow(InitError);
  });
});

describe("parseVisibilityChoice", () => {
  it("accepts short and long forms case-insensitive and trimmed", () => {
    expect(parseVisibilityChoice("o")).toBe("oss");
    expect(parseVisibilityChoice("O")).toBe("oss");
    expect(parseVisibilityChoice("oss")).toBe("oss");
    expect(parseVisibilityChoice("OSS")).toBe("oss");
    expect(parseVisibilityChoice(" oss ")).toBe("oss");
    expect(parseVisibilityChoice("p")).toBe("private");
    expect(parseVisibilityChoice("private")).toBe("private");
  });

  it("returns undefined for unrelated input", () => {
    expect(parseVisibilityChoice("internal")).toBeUndefined();
    expect(parseVisibilityChoice("1")).toBeUndefined();
    expect(parseVisibilityChoice("yes")).toBeUndefined();
  });
});

describe("parseSinceFlag", () => {
  it("accepts a valid year and the inclusive currentYear+1 upper bound", () => {
    expect(parseSinceFlag("2020", YEAR)).toBe(2020);
    expect(parseSinceFlag("2026", YEAR)).toBe(2026);
    expect(parseSinceFlag(String(YEAR + 1), YEAR)).toBe(YEAR + 1);
  });

  it("rejects non-integer, out-of-range, leading-zero, and current+2 years", () => {
    expect(() => parseSinceFlag("abc", YEAR)).toThrow(InitError);
    expect(() => parseSinceFlag("1999", YEAR)).toThrow(InitError);
    expect(() => parseSinceFlag("99999", YEAR)).toThrow(InitError);
    expect(() => parseSinceFlag(String(YEAR + 2), YEAR)).toThrow(InitError);
    expect(() => parseSinceFlag("0000", YEAR)).toThrow(InitError);
    expect(() => parseSinceFlag("02020", YEAR)).toThrow(InitError);
  });

  it("prefixes prompt-style errors with --since for flag callers", () => {
    expect(() => parseSinceFlag("1999", YEAR)).toThrow(/^--since: /);
  });
});

describe("parsePlatformFlag", () => {
  it("accepts the two long forms", () => {
    expect(parsePlatformFlag("github")).toBe("github");
    expect(parsePlatformFlag("forgejo")).toBe("forgejo");
  });

  it("rejects short forms and unknown values", () => {
    expect(() => parsePlatformFlag("g")).toThrow(InitError);
    expect(() => parsePlatformFlag("f")).toThrow(InitError);
    expect(() => parsePlatformFlag("gitlab")).toThrow(InitError);
    expect(() => parsePlatformFlag("")).toThrow(InitError);
  });
});

describe("parsePlatformChoice", () => {
  it("accepts short and long forms case-insensitive and trimmed", () => {
    expect(parsePlatformChoice("g")).toBe("github");
    expect(parsePlatformChoice("G")).toBe("github");
    expect(parsePlatformChoice("github")).toBe("github");
    expect(parsePlatformChoice("GITHUB")).toBe("github");
    expect(parsePlatformChoice(" github ")).toBe("github");
    expect(parsePlatformChoice("f")).toBe("forgejo");
    expect(parsePlatformChoice("forgejo")).toBe("forgejo");
  });

  it("returns undefined for unrelated input", () => {
    expect(parsePlatformChoice("gitlab")).toBeUndefined();
    expect(parsePlatformChoice("1")).toBeUndefined();
  });
});

describe("detectPlatform", () => {
  it("returns forgejo for a non-git directory", () => {
    const cwd = createFreshDir();
    expect(detectPlatform(cwd)).toBe("forgejo");
  });

  it("returns github when origin URL contains github.com", () => {
    const cwd = createFreshDir();
    spawnSync("git", ["-C", cwd, "init", "--quiet", "--initial-branch=main"]);
    spawnSync("git", [
      "-C",
      cwd,
      "remote",
      "add",
      "origin",
      "https://github.com/example/example.git",
    ]);
    expect(detectPlatform(cwd)).toBe("github");
  });

  it("returns forgejo for any other origin URL", () => {
    const cwd = createFreshDir();
    spawnSync("git", ["-C", cwd, "init", "--quiet", "--initial-branch=main"]);
    spawnSync("git", [
      "-C",
      cwd,
      "remote",
      "add",
      "origin",
      "https://forgejo.example.com/example/example.git",
    ]);
    expect(detectPlatform(cwd)).toBe("forgejo");
  });
});

function createPlatformFixture(platform: "forgejo" | "github" | undefined): string {
  const cwd = mkdtempSync(join(tmpdir(), "standards-platform-"));
  writeFileSync(join(cwd, "package.json"), "{}\n");
  writeFileSync(join(cwd, "README.md"), "# Demo\n");
  const meta: Record<string, unknown> = { standards: 0, visibility: "oss", since: 2020 };
  if (platform !== undefined) meta.platform = platform;
  writeFileSync(join(cwd, ".repometa.json"), `${JSON.stringify(meta, undefined, 2)}\n`);
  return cwd;
}

describe("platform filter in runApply and runCheck", () => {
  const githubCiPath = ".github/workflows/ci.yml";
  const forgejoCiPath = ".forgejo/workflows/ci.yml";

  it("writes the github-scoped CI workflow on a github repo", () => {
    const cwd = createPlatformFixture("github");
    runApply(cwd, YEAR);
    expect(existsSync(join(cwd, githubCiPath))).toBe(true);
    expect(existsSync(join(cwd, forgejoCiPath))).toBe(false);
  });

  it("writes the forgejo-scoped CI workflow on a forgejo repo", () => {
    const cwd = createPlatformFixture("forgejo");
    runApply(cwd, YEAR);
    expect(existsSync(join(cwd, forgejoCiPath))).toBe(true);
    expect(existsSync(join(cwd, githubCiPath))).toBe(false);
  });

  it("skips every platform-scoped entry on a legacy repo and refuses to bump the stamp", () => {
    const cwd = createPlatformFixture(undefined);
    const changes = runApply(cwd, YEAR);
    expect(existsSync(join(cwd, githubCiPath))).toBe(false);
    expect(existsSync(join(cwd, forgejoCiPath))).toBe(false);
    expect(changes.find((change) => change.path === ".repometa.json")).toBeUndefined();
    expect(readStamp(cwd)).toBe(0);
  });

  it("reports no drift for filtered-out entries on a forgejo repo", () => {
    const cwd = createPlatformFixture("forgejo");
    runApply(cwd, YEAR);
    const findings = runCheck(cwd, YEAR);
    expect(findings.find((f) => f.path === githubCiPath)).toBeUndefined();
    expect(findings.find((f) => f.path === forgejoCiPath)).toBeUndefined();
  });

  it("reports no drift for filtered-out entries on a github repo", () => {
    const cwd = createPlatformFixture("github");
    runApply(cwd, YEAR);
    const findings = runCheck(cwd, YEAR);
    expect(findings.find((f) => f.path === githubCiPath)).toBeUndefined();
    expect(findings.find((f) => f.path === forgejoCiPath)).toBeUndefined();
  });

  it("reports a stamp finding for legacy repos missing platform when platform-scoped entries exist", () => {
    const cwd = createPlatformFixture(undefined);
    const findings = runCheck(cwd, YEAR);
    const missing = findings.find((f) => f.detail.includes("platform is missing"));
    expect(missing).toBeDefined();
  });
});

describe("matchesPlatform", () => {
  it("entries without platform apply to every repo", () => {
    expect(matchesPlatform(undefined, "github")).toBe(true);
    expect(matchesPlatform(undefined, "forgejo")).toBe(true);
    expect(matchesPlatform(undefined, undefined)).toBe(true);
  });

  it("matching platforms apply", () => {
    expect(matchesPlatform("github", "github")).toBe(true);
    expect(matchesPlatform("forgejo", "forgejo")).toBe(true);
  });

  it("mismatched platforms are skipped", () => {
    expect(matchesPlatform("github", "forgejo")).toBe(false);
    expect(matchesPlatform("forgejo", "github")).toBe(false);
  });

  it("legacy meta (no platform) skips every platform-scoped entry", () => {
    expect(matchesPlatform("github", undefined)).toBe(false);
    expect(matchesPlatform("forgejo", undefined)).toBe(false);
  });
});

describe("detectFirstCommitYear", () => {
  it("returns undefined for a non-git directory", () => {
    const cwd = createFreshDir();
    expect(detectFirstCommitYear(cwd, YEAR)).toBeUndefined();
  });

  it("returns the root-commit year for a backdated repo", () => {
    const cwd = createFreshDir();
    initGitRepo(cwd, 2020);
    expect(detectFirstCommitYear(cwd, YEAR)).toBe(2020);
  });

  it("returns undefined when the repo has no commits", () => {
    const cwd = createFreshDir();
    spawnSync("git", ["-C", cwd, "init", "--quiet", "--initial-branch=main"]);
    expect(detectFirstCommitYear(cwd, YEAR)).toBeUndefined();
  });
});

describe("runInit", () => {
  it("writes a complete schema with all options provided", async () => {
    const cwd = createFreshDir();
    const meta = await runInit(cwd, YEAR, {
      visibility: "private",
      since: 2024,
      platform: "github",
      interactive: false,
    });
    expect(meta).toStrictEqual({
      standards: 0,
      visibility: "private",
      since: 2024,
      platform: "github",
    });

    const onDisk: unknown = JSON.parse(readFileSync(join(cwd, ".repometa.json"), "utf8"));
    expect(onDisk).toStrictEqual(meta);
  });

  it("applies defaults when no options are passed and cwd is non-git", async () => {
    const cwd = createFreshDir();
    const meta = await runInit(cwd, YEAR, { interactive: false });
    expect(meta).toStrictEqual({
      standards: 0,
      visibility: "oss",
      since: YEAR,
      platform: "forgejo",
    });
  });

  it("uses the git root-commit year for the since default", async () => {
    const cwd = createFreshDir();
    initGitRepo(cwd, 2020);
    const meta = await runInit(cwd, YEAR, { interactive: false });
    expect(meta.since).toBe(2020);
  });

  it("detects platform from origin URL in non-interactive mode", async () => {
    const cwd = createFreshDir();
    spawnSync("git", ["-C", cwd, "init", "--quiet", "--initial-branch=main"]);
    spawnSync("git", [
      "-C",
      cwd,
      "remote",
      "add",
      "origin",
      "https://github.com/example/example.git",
    ]);
    const meta = await runInit(cwd, YEAR, { interactive: false });
    expect(meta.platform).toBe("github");
  });

  it("refuses to overwrite an existing file without force", async () => {
    const cwd = createFreshDir();
    writeFileSync(join(cwd, ".repometa.json"), "{}\n");
    await expect(runInit(cwd, YEAR, { interactive: false })).rejects.toThrow(/already exists/);
    await expect(runInit(cwd, YEAR, { interactive: false })).rejects.toThrow(/--force/);
  });

  it("overwrites when force is set", async () => {
    const cwd = createFreshDir();
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify({ standards: 2, visibility: "oss", since: 2024 }, undefined, 2)}\n`,
    );
    const meta = await runInit(cwd, YEAR, { interactive: false, force: true });
    expect(meta.standards).toBe(0);
  });

  it("resets a stamp it cannot read instead of refusing to force", async () => {
    // `--force` is also the way out of a broken stamp, so an unreadable file
    // is a warning, not a failure.
    const cwd = createFreshDir();
    writeFileSync(join(cwd, ".repometa.json"), "{ not json\n");
    const { input, output, captured } = createCapturedStreams();

    const meta = await runInit(cwd, YEAR, {
      interactive: false,
      force: true,
      platform: "github",
      streams: { input, output },
    });

    expect(meta.standards).toBe(0);
    expect(meta.workspaces).toBeUndefined();
    expect(captured.current).toContain("could not be read");
  });

  it("keeps the fields it does not ask about when forcing", async () => {
    // `init --force --platform github` is the documented migration for a legacy
    // stamp; the repository's own declarations must survive it.
    const cwd = createFreshDir();
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify(
        {
          standards: 6,
          visibility: "oss",
          since: 2024,
          exceptions: ["keeps-prettier"],
          workspaces: ["node"],
          readme: { owner: "markdown-themer" },
        },
        undefined,
        2,
      )}\n`,
    );

    const meta = await runInit(cwd, YEAR, { interactive: false, force: true, platform: "github" });

    expect(meta.exceptions).toStrictEqual(["keeps-prettier"]);
    expect(meta.workspaces).toStrictEqual(["node"]);
    expect(meta.readme).toStrictEqual({ owner: "markdown-themer" });
    expect(meta.platform).toBe("github");
  });
});

type CapturedRun = {
  input: PassThrough;
  output: Writable;
  captured: { current: string };
};

function createCapturedStreams(): CapturedRun {
  const captured = { current: "" };
  const output = new Writable({
    write(chunk, _encoding, callback) {
      captured.current += String(chunk);
      callback();
    },
  });
  return { input: new PassThrough(), output, captured };
}

async function feedInput(input: PassThrough, lines: string[]): Promise<void> {
  for (const line of lines) {
    input.write(`${line}\n`);
    await new Promise<void>((resolve) => {
      setImmediate(resolve);
    });
  }
}

describe("runInit interactive prompt loop", () => {
  it("accepts single-letter shortcuts and returns the parsed values", async () => {
    const cwd = createFreshDir();
    const { input, output, captured } = createCapturedStreams();
    const initPromise = runInit(cwd, YEAR, {
      interactive: true,
      streams: { input, output },
    });
    void feedInput(input, ["p", "2018", "g"]);

    const meta = await initPromise;
    expect(meta).toStrictEqual({
      standards: 0,
      visibility: "private",
      since: 2018,
      platform: "github",
    });
    expect(captured.current).toContain("Repository visibility");
    expect(captured.current).toContain("(o) open source");
    expect(captured.current).toContain("Repository platform");
    expect(captured.current).toContain("(g) GitHub");
  });

  it("applies defaults on empty input", async () => {
    const cwd = createFreshDir();
    const { input, output } = createCapturedStreams();
    const initPromise = runInit(cwd, YEAR, {
      interactive: true,
      streams: { input, output },
    });
    void feedInput(input, ["", "", ""]);

    const meta = await initPromise;
    expect(meta).toStrictEqual({
      standards: 0,
      visibility: "oss",
      since: YEAR,
      platform: "forgejo",
    });
  });

  it("re-prompts after invalid visibility, then accepts a valid value", async () => {
    const cwd = createFreshDir();
    const { input, output, captured } = createCapturedStreams();
    const initPromise = runInit(cwd, YEAR, {
      interactive: true,
      streams: { input, output },
      platform: "github",
    });
    void feedInput(input, ["x", "oss", "2020"]);

    const meta = await initPromise;
    expect(meta.visibility).toBe("oss");
    expect(captured.current).toContain("Please answer o, p, oss, or private.");
  });

  it("re-prompts after invalid year, then accepts a valid value", async () => {
    const cwd = createFreshDir();
    const { input, output, captured } = createCapturedStreams();
    const initPromise = runInit(cwd, YEAR, {
      interactive: true,
      streams: { input, output },
      platform: "github",
    });
    void feedInput(input, ["o", "1999", "2020"]);

    const meta = await initPromise;
    expect(meta.since).toBe(2020);
    expect(captured.current).toContain("Year must be");
    expect(captured.current).not.toContain("--since");
  });

  it("aborts after 3 invalid visibility attempts", async () => {
    const cwd = createFreshDir();
    const { input, output } = createCapturedStreams();
    const initPromise = runInit(cwd, YEAR, {
      interactive: true,
      streams: { input, output },
    });
    void feedInput(input, ["x", "y", "z"]);

    await expect(initPromise).rejects.toThrow(/Too many invalid attempts for visibility/);
  });

  it("aborts after 3 invalid year attempts", async () => {
    const cwd = createFreshDir();
    const { input, output } = createCapturedStreams();
    const initPromise = runInit(cwd, YEAR, {
      interactive: true,
      streams: { input, output },
    });
    void feedInput(input, ["o", "abc", "1999", "99999"]);

    await expect(initPromise).rejects.toThrow(/Too many invalid attempts for initial year/);
  });

  it("aborts after 3 invalid platform attempts", async () => {
    const cwd = createFreshDir();
    const { input, output } = createCapturedStreams();
    const initPromise = runInit(cwd, YEAR, {
      interactive: true,
      streams: { input, output },
    });
    void feedInput(input, ["o", "2020", "x", "y", "z"]);

    await expect(initPromise).rejects.toThrow(/Too many invalid attempts for platform/);
  });
});

describe("runInit write contract", () => {
  it("modifies only .repometa.json", async () => {
    const cwd = createFreshDir();
    const foreign = ["src/x.ts", ".gitignore", "docs/notes.md"];
    foreign.forEach((rel) => {
      const target = join(cwd, rel);
      mkdirSync(join(target, ".."), { recursive: true });
      writeFileSync(target, `foreign:${rel}\n`);
    });

    const before = hashTree(cwd);
    await runInit(cwd, YEAR, { interactive: false });
    const after = hashTree(cwd);

    const modifiedPaths = [...after.entries()]
      .filter(([path, hash]) => before.get(path) !== hash)
      .map(([path]) => path);
    const removedPaths = [...before.keys()].filter((path) => !after.has(path));
    expect([...modifiedPaths, ...removedPaths]).toStrictEqual([".repometa.json"]);

    const preservedForeign = foreign.map((rel) => readFileSync(join(cwd, rel), "utf8"));
    expect(preservedForeign).toStrictEqual(foreign.map((rel) => `foreign:${rel}\n`));
  });
});

describe("initCommand TTY injection", () => {
  it("throws on non-TTY without --yes", async () => {
    const cwd = createFreshDir();
    await expect(initCommand({ cwd, currentYear: YEAR, args: [], isTty: false })).rejects.toThrow(
      /No TTY/,
    );
  });

  it("writes the file in non-interactive mode with --yes regardless of TTY", async () => {
    const cwd = createFreshDir();
    await initCommand({
      cwd,
      currentYear: YEAR,
      args: ["--yes", "--visibility", "private", "--since", "2024"],
      isTty: false,
    });
    expect(existsSync(join(cwd, ".repometa.json"))).toBe(true);
    expect(readStamp(cwd)).toBe(0);
  });
});

describe("published binary", () => {
  it("bin wrapper starts with a node shebang", async () => {
    const { getPackageRoot } = await import("../src/manifest.js");
    const wrapper = readFileSync(join(getPackageRoot(), "bin/standards.js"), "utf8");
    expect(wrapper.startsWith("#!/usr/bin/env node\n")).toBe(true);
  });
});

describe("standards init CLI guard", () => {
  it("fails fast with a No TTY hint when stdin is piped and --yes is absent", async () => {
    const { getPackageRoot } = await import("../src/manifest.js");
    const cliPath = join(getPackageRoot(), "dist", "cli.js");
    const fixtureCwd = mkdtempSync(join(tmpdir(), "standards-cli-"));

    const result = spawnSync(process.execPath, [cliPath, "init", "--cwd", fixtureCwd], {
      encoding: "utf8",
      input: "",
      stdio: ["pipe", "pipe", "pipe"],
    });

    expect(result.status).not.toBe(0);
    expect(result.stderr).toMatch(/No TTY/);
  });
});

function currentStandardsVersion(): number {
  return loadManifest(standardsRoot()).currentVersion;
}

/**
 * A fixture that is fully applied and then re-stamped, so the only difference
 * from a clean repository is the version stamp itself.
 */
function createStampedFixture(stamp: number): string {
  const cwd = createFixtureRepo();
  runApply(cwd, YEAR);
  const raw: unknown = JSON.parse(readFileSync(join(cwd, ".repometa.json"), "utf8"));
  const meta = isRecord(raw) ? raw : {};
  writeFileSync(
    join(cwd, ".repometa.json"),
    `${JSON.stringify({ ...meta, standards: stamp }, undefined, 2)}\n`,
  );
  return cwd;
}

function runCli(args: string[]): { status: null | number; stdout: string; stderr: string } {
  const cliPath = join(standardsRoot(), "dist", "cli.js");
  const result = spawnSync(process.execPath, [cliPath, ...args], { encoding: "utf8" });
  return { status: result.status, stdout: result.stdout, stderr: result.stderr };
}

function stampFindingOf(cwd: string): Finding {
  return unwrap(runCheck(cwd, YEAR).find((finding) => finding.kind === "stamp"));
}

describe("CLI and stamp alignment", () => {
  it("reports a repository behind the installed CLI as non-blocking drift", () => {
    const cwd = createStampedFixture(currentStandardsVersion() - 1);

    const finding = stampFindingOf(cwd);
    expect(finding.blocking).toBe(false);
    expect(finding.detail).toContain("the repository is behind the installed CLI");
    expect(finding.detail).toContain("see changes/ for migration steps");
    expect(runCli(["check", "--cwd", cwd]).status).toBe(1);
  });

  it("bumps the stamp of a repository behind the installed CLI", () => {
    const current = currentStandardsVersion();
    const cwd = createStampedFixture(current - 1);

    const changes = runApply(cwd, YEAR);

    expect(changes.find((change) => change.action === "bumped")).toBeDefined();
    expect(readStamp(cwd)).toBe(current);
  });

  it("reports an installed CLI behind the repository as blocking, and names the fix", () => {
    const cwd = createStampedFixture(currentStandardsVersion() + 1);

    const finding = stampFindingOf(cwd);
    expect(finding.blocking).toBe(true);
    expect(finding.detail).toContain("the installed CLI is behind the repository");
    expect(finding.detail).toContain("Raise the `@sebastian-software/standards` pin");
    expect(finding.detail).toContain("refresh the lockfile");
    expect(runCli(["check", "--cwd", cwd]).status).toBe(3);
  });

  it("keeps the stamp when a stale CLI applies without --from-version", () => {
    const stamp = currentStandardsVersion() + 1;
    const cwd = createStampedFixture(stamp);

    const changes = runApply(cwd, YEAR);

    expect(changes.find((change) => change.path === ".repometa.json")).toBeUndefined();
    expect(readStamp(cwd)).toBe(stamp);
    // The evidence survives, so the next `check` still reports the mismatch.
    expect(stampFindingOf(cwd).blocking).toBe(true);
  });

  it("writes no repository content at all when a stale CLI applies", () => {
    // The stamp is not the only thing at stake: a stale CLI's references
    // belong to an earlier standards version, so writing them would downgrade
    // managed content and sections while the stamp still claims the newer
    // version — a worse state than the misalignment being preserved.
    const stamp = currentStandardsVersion() + 1;
    const cwd = createStampedFixture(stamp);
    const driftedManaged = "{}\n";
    const driftedSection =
      "<!-- sebastian-software-consumer-agents:start -->\nstale\n<!-- sebastian-software-consumer-agents:end -->\n";
    writeFileSync(join(cwd, ".oxfmtrc.json"), driftedManaged);
    writeFileSync(join(cwd, "AGENTS.md"), driftedSection);

    const changes = runApply(cwd, YEAR);

    expect(changes).toStrictEqual([]);
    expect(readFileSync(join(cwd, ".oxfmtrc.json"), "utf8")).toBe(driftedManaged);
    expect(readFileSync(join(cwd, "AGENTS.md"), "utf8")).toBe(driftedSection);
    expect(readStamp(cwd)).toBe(stamp);
  });

  it("seeds nothing when a stale CLI applies to a fresh repository", () => {
    const cwd = createFixtureRepo();
    writeFileSync(
      join(cwd, ".repometa.json"),
      `${JSON.stringify(
        {
          standards: currentStandardsVersion() + 1,
          visibility: "oss",
          since: 2020,
          platform: "github",
        },
        undefined,
        2,
      )}\n`,
    );

    expect(runApply(cwd, YEAR)).toStrictEqual([]);
    expect(existsSync(join(cwd, "eslint.config.ts"))).toBe(false);
    expect(existsSync(join(cwd, ".oxfmtrc.json"))).toBe(false);
  });

  it("still self-heals the stamp when --from-version was supplied", () => {
    const current = currentStandardsVersion();
    const cwd = createStampedFixture(current + 1);

    const changes = runApply(cwd, YEAR, { explicitFromVersion: true });

    expect(changes.find((change) => change.action === "bumped")).toBeDefined();
    expect(readStamp(cwd)).toBe(current);
  });

  it("threads --from-version from the CLI, so the Renovate path keeps self-healing", () => {
    const current = currentStandardsVersion();
    const guarded = createStampedFixture(current + 1);
    const healed = createStampedFixture(current + 1);

    expect(runCli(["apply", "--cwd", guarded]).status).toBe(3);
    expect(readStamp(guarded)).toBe(current + 1);

    expect(runCli(["apply", "--cwd", healed, "--from-version", "0"]).status).toBe(0);
    expect(readStamp(healed)).toBe(current);
  });

  it("reports nothing and exits 0 when the versions match", () => {
    const cwd = createFixtureRepo();
    runApply(cwd, YEAR);

    expect(runCheck(cwd, YEAR)).toStrictEqual([]);
    expect(runCli(["check", "--cwd", cwd]).status).toBe(0);
  });

  it("keeps the missing-platform stamp finding non-blocking", () => {
    const cwd = createPlatformFixture(undefined);

    const findings = runCheck(cwd, YEAR);
    const missing = unwrap(findings.find((f) => f.detail.includes("platform is missing")));
    expect(missing.blocking).toBe(false);
    // The legacy platform block still takes precedence over the stamp bump.
    expect(runApply(cwd, YEAR).find((change) => change.path === ".repometa.json")).toBeUndefined();
  });
});

/**
 * The guard that stops a stale CLI from writing made `apply` and `sync` silent
 * rather than loud: both used to finish with exit `0` and a success line for a
 * repository `standards check` refuses with exit `3`. They now speak `check`'s
 * own directional message and carry its exit code.
 */
describe("stale CLI in apply and sync", () => {
  const directional = "the installed CLI is behind the repository";

  it("reports the blocking mismatch from sync and dispatches no agent", () => {
    const cwd = createStampedFixture(currentStandardsVersion() + 1);

    // `--dry-run` prints the agent prompt, so its absence proves no prompt was
    // built — and therefore that no `claude`/`codex` process was ever a step away.
    const result = runCli(["sync", "--cwd", cwd, "--dry-run"]);

    expect(result.status).toBe(3);
    expect(result.stdout).toContain(directional);
    expect(result.stdout).toContain("Raise the `@sebastian-software/standards` pin");
    expect(result.stdout).not.toContain("No changelog entries require agent work");
    expect(result.stdout).not.toContain("Running ");
    expect(result.stdout).not.toContain("Pre-flight");
  });

  it("reports the blocking mismatch from apply and writes nothing", () => {
    const stamp = currentStandardsVersion() + 1;
    const cwd = createStampedFixture(stamp);
    const drifted = "{}\n";
    writeFileSync(join(cwd, ".oxfmtrc.json"), drifted);

    const result = runCli(["apply", "--cwd", cwd]);

    expect(result.status).toBe(3);
    expect(result.stdout).toContain(directional);
    expect(result.stdout).not.toContain("Already up to date");
    expect(result.stdout).not.toContain("Applied ");
    expect(readFileSync(join(cwd, ".oxfmtrc.json"), "utf8")).toBe(drifted);
    expect(readStamp(cwd)).toBe(stamp);
  });

  it("leaves apply --from-version alone, so Renovate keeps self-healing", () => {
    const current = currentStandardsVersion();
    const cwd = createStampedFixture(current + 1);

    const result = runCli(["apply", "--cwd", cwd, "--from-version", String(current)]);

    expect(result.status).toBe(0);
    expect(result.stdout).not.toContain(directional);
    expect(readStamp(cwd)).toBe(current);
  });

  it("keeps both commands green when the stamp matches the manifest", () => {
    const cwd = createFixtureRepo();
    runApply(cwd, YEAR);

    const applied = runCli(["apply", "--cwd", cwd]);
    expect(applied.status).toBe(0);
    expect(applied.stdout).toContain("Already up to date");

    const synced = runCli(["sync", "--cwd", cwd, "--dry-run"]);
    expect(synced.status).toBe(0);
    expect(synced.stdout).toContain("No changelog entries require agent work");
  });

  it("stays quiet for a repository behind its CLI, which apply still repairs", () => {
    const current = currentStandardsVersion();
    const cwd = createStampedFixture(current - 1);

    const result = runCli(["apply", "--cwd", cwd]);

    expect(result.status).toBe(0);
    expect(result.stdout).not.toContain(directional);
    expect(readStamp(cwd)).toBe(current);
  });
});

type CheckJsonReport = {
  findings: Array<Record<string, unknown>>;
  total: unknown;
  blocking: unknown;
};

function parseCheckJson(stdout: string): CheckJsonReport {
  const raw: unknown = JSON.parse(stdout);
  if (!isRecord(raw) || !isUnknownArray(raw.findings)) {
    throw new TypeError("standards check --json did not write the documented object");
  }
  return {
    findings: raw.findings.map((entry) => {
      if (!isRecord(entry)) {
        throw new TypeError("standards check --json wrote a non-object finding");
      }
      return entry;
    }),
    total: raw.total,
    blocking: raw.blocking,
  };
}

describe("standards check --json", () => {
  it("writes one object and no prose for a clean repository", () => {
    const cwd = createFixtureRepo();
    runApply(cwd, YEAR);

    const result = runCli(["check", "--cwd", cwd, "--json"]);

    expect(result.status).toBe(0);
    expect(result.stdout).not.toContain("✓");
    expect(JSON.parse(result.stdout)).toStrictEqual({ findings: [], total: 0, blocking: 0 });
  });

  it("carries the blocking class in the payload and in the exit code", () => {
    const cwd = createStampedFixture(currentStandardsVersion() + 1);

    const result = runCli(["check", "--cwd", cwd, "--json"]);

    expect(result.status).toBe(3);
    expect(result.stdout).not.toContain("finding(s)");
    const parsed = parseCheckJson(result.stdout);
    expect(parsed.total).toBe(1);
    expect(parsed.blocking).toBe(1);
    const first = unwrap(parsed.findings[0]);
    expect(Object.keys(first).toSorted()).toStrictEqual(["blocking", "detail", "kind", "path"]);
    expect(first.kind).toBe("stamp");
    expect(first.path).toBe(".repometa.json");
    expect(first.blocking).toBe(true);
  });

  it("counts a non-blocking finding without raising the exit code to 3", () => {
    const cwd = createStampedFixture(currentStandardsVersion() - 1);

    const result = runCli(["check", "--cwd", cwd, "--json"]);

    expect(result.status).toBe(1);
    const parsed = parseCheckJson(result.stdout);
    expect(parsed.total).toBe(1);
    expect(parsed.blocking).toBe(0);
  });
});

describe("assertBlockedState", () => {
  const validState = {
    schemaVersion: 1,
    blocking: true,
    reason: "The pinned CLI ships manifest version 12, but .repometa.json is stamped 13.",
    detectedAt: "2026-09-07T09:41:12.000Z",
    expectedStandardsVersion: 13,
    observedStandardsVersion: 13,
    expectedCliVersion: "0.10.0",
    observedCliVersion: "0.9.0",
    failedChecks: ["standards check"],
    retry: "Raise the pin, refresh the lockfile, re-run the gate, then delete this file.",
  };

  it("accepts a fully populated marker", () => {
    expect(() => {
      assertBlockedState(validState);
    }).not.toThrow();
  });

  it("accepts nulls where a value could not be read", () => {
    const unknownValues = {
      ...validState,
      blocking: false,
      observedStandardsVersion: null,
      expectedCliVersion: null,
      observedCliVersion: null,
      failedChecks: [],
    };
    expect(() => {
      assertBlockedState(unknownValues);
    }).not.toThrow();
  });

  it("rejects the wrong schemaVersion", () => {
    expect(() => {
      assertBlockedState({ ...validState, schemaVersion: 2 });
    }).toThrow(/schemaVersion/);
  });

  it("rejects a non-boolean blocking flag", () => {
    expect(() => {
      assertBlockedState({ ...validState, blocking: "true" });
    }).toThrow(/blocking/);
  });

  it("rejects a missing expectedStandardsVersion", () => {
    const { expectedStandardsVersion, ...rest } = validState;
    void expectedStandardsVersion;
    expect(() => {
      assertBlockedState(rest);
    }).toThrow(/expectedStandardsVersion/);
  });

  it("rejects failedChecks that is not an array of strings", () => {
    expect(() => {
      assertBlockedState({ ...validState, failedChecks: "standards check" });
    }).toThrow(/failedChecks/);
  });

  it("rejects a missing retry sentence", () => {
    const { retry, ...rest } = validState;
    void retry;
    expect(() => {
      assertBlockedState(rest);
    }).toThrow(/retry/);
  });

  it("rejects a non-object", () => {
    expect(() => {
      assertBlockedState(null);
    }).toThrow(/expected an object/);
  });
});

/** A marker that satisfies `BlockedState`, as documented in `SKILL.md`. */
const VALID_MARKER = {
  schemaVersion: 1,
  blocking: true,
  reason: "The pinned CLI ships manifest version 12, but .repometa.json is stamped 13.",
  detectedAt: "2026-09-07T09:41:12.000Z",
  expectedStandardsVersion: 13,
  observedStandardsVersion: 13,
  expectedCliVersion: "0.10.0",
  observedCliVersion: "0.9.0",
  failedChecks: ["standards check"],
  retry: "Raise the pin, refresh the lockfile, re-run the gate, then delete this file.",
};

/**
 * The body of the workflow's `node -e "…"` marker guard. Reading it out of the
 * workflow rather than restating it is what makes the tests below exercise the
 * script CI actually runs. Every string inside that script is single-quoted, so
 * the first double quote after the flag terminates it.
 */
function markerGuardScriptOf(file: string): string {
  const workflow = readFileSync(join(standardsRoot(), file), "utf8");
  const step = workflow.slice(workflow.indexOf('- name: "Guard: no blocking agent findings'));
  const flag = 'node -e "';
  const start = step.indexOf(flag) + flag.length;
  return step.slice(start, step.indexOf('"', start));
}

function runMarkerGuard(
  file: string,
  marker?: string,
): { status: null | number; stderr: string; stdout: string } {
  const cwd = mkdtempSync(join(tmpdir(), "standards-guard-"));
  if (marker !== undefined) {
    mkdirSync(join(cwd, ".standards"), { recursive: true });
    writeFileSync(join(cwd, ".standards", "blocked.json"), marker);
  }
  const result = spawnSync(process.execPath, ["-e", markerGuardScriptOf(file)], {
    cwd,
    encoding: "utf8",
  });
  return { status: result.status, stdout: result.stdout, stderr: result.stderr };
}

describe("seeded CI guards for alignment and the blocked marker", () => {
  const nodeWorkflows = [
    "reference/node/github-workflows-ci.yml",
    "reference/node/forgejo-workflows-ci.yml",
  ];

  it.each(nodeWorkflows)("%s resolves the manifest and compares it to the stamp", (file) => {
    const workflow = readFileSync(join(standardsRoot(), file), "utf8");

    expect(workflow).toContain("require.resolve('@sebastian-software/standards/manifest.json'");
    // Nested workspaces per change 0012 are searched as well.
    expect(workflow).toContain("meta.workspaces");
    expect(workflow).toContain("manifest.currentVersion !== meta.standards");
    // `jq` is not guaranteed in the Forgejo node image, so no step may call it.
    const executable = workflow
      .split("\n")
      .filter((line) => !line.trimStart().startsWith("#"))
      .join("\n");
    expect(executable).not.toContain("jq");
    // The guard sits immediately before the drift lane, so a lint or test
    // failure in the same run stays visible to a reviewer.
    expect(workflow.indexOf("matches the repository stamp")).toBeLessThan(
      workflow.indexOf("pnpm exec standards check"),
    );
  });

  const guardedWorkflows = [...nodeWorkflows, "reference/rust/ci.yml"];

  it.each(guardedWorkflows)("%s places the marker guard where it can run", (file) => {
    const workflow = readFileSync(join(standardsRoot(), file), "utf8");

    expect(workflow).toContain(".standards/blocked.json");
    // The marker guard follows the pending guard it complements.
    expect(workflow.indexOf("test ! -f .standards/pending.json")).toBeLessThan(
      workflow.indexOf("no blocking agent findings"),
    );
    // It parses the marker with `node`, so the toolchain has to be set up
    // first — in the Rust workflow the guard sits below the node setup for
    // exactly this reason.
    expect(workflow.indexOf("actions/setup-node")).toBeLessThan(
      workflow.indexOf("no blocking agent findings"),
    );
    // A line-oriented match is what let a multi-line marker through.
    expect(workflow).not.toContain("[[:space:]]");
  });

  it.each(guardedWorkflows)("%s passes a repository without a marker", (file) => {
    expect(runMarkerGuard(file).status).toBe(0);
  });

  it.each(guardedWorkflows)("%s passes a valid non-blocking marker", (file) => {
    const result = runMarkerGuard(file, JSON.stringify({ ...VALID_MARKER, blocking: false }));

    expect(result.status).toBe(0);
    expect(result.stdout).toContain("non-blocking");
  });

  it.each(guardedWorkflows)("%s fails on a blocking marker", (file) => {
    const result = runMarkerGuard(file, JSON.stringify(VALID_MARKER));

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("could not validate its result");
  });

  it.each(guardedWorkflows)("%s fails on a blocking flag split across lines", (file) => {
    // The exact shape the line-oriented `grep` missed: JSON permits a newline
    // between the key and its value, and the marker still records a blocking
    // result.
    const marker = JSON.stringify(VALID_MARKER, undefined, 2).replace(
      '"blocking": true',
      '"blocking":\n    true',
    );
    expect(marker).not.toContain('"blocking": true');

    const result = runMarkerGuard(file, marker);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("could not validate its result");
  });

  it.each(guardedWorkflows)("%s fails on a marker that is not valid JSON", (file) => {
    const result = runMarkerGuard(file, '{ "blocking": tru\n');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("not valid JSON");
  });

  it.each(guardedWorkflows)("%s fails on a marker that violates the schema", (file) => {
    const { retry, ...withoutRetry } = VALID_MARKER;
    void retry;

    const result = runMarkerGuard(file, JSON.stringify({ ...withoutRetry, blocking: false }));

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("does not match the documented schema");
    expect(result.stderr).toContain("retry");
  });

  it.each(guardedWorkflows)("%s fails on a marker that is not an object", (file) => {
    const result = runMarkerGuard(file, "[]\n");

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("not a JSON object");
  });

  it("validates every field the authoritative schema declares", () => {
    const guard = markerGuardScriptOf("reference/node/github-workflows-ci.yml");

    for (const field of Object.keys(VALID_MARKER)) {
      expect(guard).toContain(field);
    }
  });
});
