import { existsSync, lstatSync, readFileSync } from "node:fs";
import { join } from "node:path";

import type { ReadmeOwnership } from "./repo.js";

export const MARKDOWN_THEMER_CONFIG_FILENAMES = [
  "markdown-themer.config.ts",
  "markdown-themer.config.mts",
  "markdown-themer.config.js",
  "markdown-themer.config.mjs",
] as const;

const GENERATED_NOTICE =
  "<!-- This file is generated by markdown-themer. Edit README.md.src instead. -->";
const LEGACY_BRANDING_MARKER = /<!--\s*sebastian-software-branding:(?:start|end)\s*-->/u;

export type MarkdownThemerMigrationIssue = {
  path: string;
  detail: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function regularFile(path: string): boolean {
  try {
    const info = lstatSync(path);
    return info.isFile();
  } catch {
    return false;
  }
}

function readUtf8(path: string): string | undefined {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return undefined;
  }
}

function packageScripts(cwd: string): Record<string, unknown> | undefined {
  const raw = readUtf8(join(cwd, "package.json"));
  if (raw === undefined) return undefined;
  try {
    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed)) return undefined;
    if (!("scripts" in parsed)) return {};
    const scripts = parsed.scripts;
    return isRecord(scripts) ? scripts : undefined;
  } catch {
    return undefined;
  }
}

function validReadmeScript(value: unknown, operation: "--check" | "--write"): boolean {
  if (typeof value !== "string") return false;
  const command = value.trim();
  return command === `markdown-themer ${operation}` || command === `node dist/cli.js ${operation}`;
}

function sourceIssues(cwd: string, owner: string): MarkdownThemerMigrationIssue[] {
  const issues: MarkdownThemerMigrationIssue[] = [];
  const source = join(cwd, "README.md.src");
  if (!regularFile(source)) {
    issues.push({
      path: "README.md.src",
      detail: `${owner} source must be a regular non-symlink file at the repository root`,
    });
  }
  const sourceContent = regularFile(source) ? readUtf8(source) : undefined;
  if (sourceContent !== undefined && LEGACY_BRANDING_MARKER.test(sourceContent)) {
    issues.push({
      path: "README.md.src",
      detail:
        "remove the legacy sebastian-software-branding marker from README.md.src before generating README.md",
    });
  }
  return issues;
}

function outputIssues(cwd: string, owner: string): MarkdownThemerMigrationIssue[] {
  const issues: MarkdownThemerMigrationIssue[] = [];
  const output = join(cwd, "README.md");
  const outputIsRegular = regularFile(output);
  const outputContent = outputIsRegular ? readUtf8(output) : undefined;
  if (!outputIsRegular) {
    issues.push({
      path: "README.md",
      detail: `${owner} output must be a regular non-symlink file at the repository root`,
    });
  } else if (
    outputContent?.split(/\r?\n/u)[0] !== GENERATED_NOTICE.replace("markdown-themer", owner)
  ) {
    issues.push({
      path: "README.md",
      detail: `README.md is missing the ${owner} generated-file notice; run ${owner} --write`,
    });
  }
  if (outputContent !== undefined && LEGACY_BRANDING_MARKER.test(outputContent)) {
    issues.push({
      path: "README.md",
      detail: `remove the legacy sebastian-software-branding marker; ${owner} owns README branding`,
    });
  }
  return issues;
}

function configIssues(cwd: string, owner: string): MarkdownThemerMigrationIssue[] {
  const filenames =
    owner === "mdtheme" ? ["mdtheme.yaml", "mdtheme.yml"] : MARKDOWN_THEMER_CONFIG_FILENAMES;
  const configPattern = owner === "mdtheme" ? "mdtheme.yaml" : "markdown-themer.config.*";
  const configs = filenames.filter((name) => existsSync(join(cwd, name)));
  if (configs.length === 0) {
    return [
      {
        path: configPattern,
        detail: `exactly one supported ${owner} config is required at the repository root`,
      },
    ];
  }
  if (configs.length > 1) {
    return [
      {
        path: configPattern,
        detail: `multiple supported configs found (${configs.join(", ")}); keep exactly one`,
      },
    ];
  }
  const config = configs[0];
  if (config !== undefined && regularFile(join(cwd, config))) return [];
  return [
    {
      path: config ?? configPattern,
      detail: `the ${owner} config must be a regular non-symlink file`,
    },
  ];
}

function packageIssues(cwd: string): MarkdownThemerMigrationIssue[] {
  const scripts = packageScripts(cwd);
  if (scripts === undefined) {
    return [
      {
        path: "package.json",
        detail: "package.json with scripts is required for markdown-themer wiring",
      },
    ];
  }
  const issues: MarkdownThemerMigrationIssue[] = [];
  if (!validReadmeScript(scripts["readme:write"], "--write")) {
    issues.push({
      path: "package.json",
      detail:
        "scripts.readme:write must invoke `markdown-themer --write` or `node dist/cli.js --write`",
    });
  }
  if (!validReadmeScript(scripts["readme:check"], "--check")) {
    issues.push({
      path: "package.json",
      detail:
        "scripts.readme:check must invoke `markdown-themer --check` or `node dist/cli.js --check`",
    });
  }
  return issues;
}

/** Check ownership prerequisites without loading or executing configuration. */
export function readmeMigrationIssues(
  cwd: string,
  owner: ReadmeOwnership["owner"] = "markdown-themer",
): MarkdownThemerMigrationIssue[] {
  return [
    ...sourceIssues(cwd, owner),
    ...outputIssues(cwd, owner),
    ...configIssues(cwd, owner),
    ...(owner === "markdown-themer" ? packageIssues(cwd) : []),
  ];
}
